### ISSUE TITLE
DebevecCRF error.

### ISSUE THREAD

**Issue by t2ac32** [adegirmenci/HDR-US#1]
Hi been trying to do a test run.
Any ideas on why is this error happening?

![image](https://user-images.githubusercontent.com/3275434/54497694-20c22c00-48fe-11e9-9bd8-090fe095c807.png)

I also tried with the commented line 78 in runHDRUS.m

`[lin_fun, ~] = DebevecCRF(stack, stack_exposure);`

Which produces:
![image](https://user-images.githubusercontent.com/3275434/54497748-94fccf80-48fe-11e9-8f6d-9014cc0d1acd.png)

**Comment by adegirmenci** [comment]
I am not able to reproduce this error on my machine. Did you run the `installHDRUS.m` script before running `runHDRUS.m`?

**Comment by adegirmenci** [comment]
You might be missing the HDR_Toolbox submodule, please run
```
git submodule init 
git submodule update
```
and then try running the `installHDRUS` and `runHDRUS` scripts.

**Comment by t2ac32** [comment]
> You might be missing the HDR_Toolbox submodule, please run
> 
> ```
> git submodule init 
> git submodule update
> ```
> and then try running the `installHDRUS` and `runHDRUS` scripts.

This did the trick thank you !
