### ISSUE TITLE
TMO Results in relation to Response Curve

### ISSUE THREAD

**Issue by t2ac32** [adegirmenci/HDR-US#2]
Good Day I've been working on running the matlab script to my own US acquired images.

During the experiments I encountered some things i would like to ask  for some insight on why is it happening.

These are the acquisition parameters:
```
Images with compresion from 0 to -14 dB  on step of 1.
     e.j:    [0 dB, -1dB , . . . , -13dB, -14dB ]
Frequency 6.6 MHz
Dynamic 80dB
Depth 4.0 cm
FPS 14 Hz
```
Is worth to mention that my response curve isn't the best (Due to bad US calibration perhaps?) which makes me think this is affecting the signal to noise ratio. 
_Experiment 1:_  (jpg images taken directly from US, borders removed.
![image](https://user-images.githubusercontent.com/3275434/55482722-6c2a4900-5625-11e9-8fed-f96b833b300e.png)
_Final Experiment:_ _32 bit images taken from US, converted to jpeg, manually added channels from 1 to 3_
![image](https://user-images.githubusercontent.com/3275434/55482550-0ccc3900-5625-11e9-869b-1b2f3ca65112.png)

Unfortunally after many tries i notice my TMO similarty maps seem to be really bad.
_Experiment 1:_ 
![image](https://user-images.githubusercontent.com/3275434/55482861-ac89c700-5625-11e9-91ae-7920f01cba5d.png)

_Final Experiment_
![image](https://user-images.githubusercontent.com/3275434/55482576-1eaddc00-5625-11e9-8854-fba59c4686d9.png)

Which makes me think there's something with my rgb convertion not giving enough information for the TMO's to be correct or wrong image acquisition process. 

**Obtained HDR images:**
_Experiment 1_ 
![image](https://user-images.githubusercontent.com/3275434/55482777-8a904480-5625-11e9-9cd3-fcc6af288279.png)

_Final Experiment_ 

![image](https://user-images.githubusercontent.com/3275434/55483328-a7794780-5626-11e9-8b58-8b0a8bbd064d.png)

 **Is there any special pre-processing or way on how images are being converted in jpeg from the Ultrasound you take them from?**

**Is my response function not good enough due to US calibration or acquisition?**

Thanks on advance !

**Comment by adegirmenci** [comment]
Hi @t2ac32. Have you fully removed the black regions around your ultrasound image? If these black pixels are not cropped out, then the response curve calculations will be completely wrong.

Another problem could be a mismatch in bit-precision. You said you are using 32bit images? The pipeline expects `uint8`.

Finally, how are you naming the image files? Check to make sure that the file order from ReadLDRStack matches the exposure order. For example `*_1,jpg, *_2.jpg, ... *_11.jpg` will be imported out of order [1, 11, 2]. This can be fixed by renaming the files to `*_01.jpg, *_02.jpg, ... *_11.jpg`

**Comment by t2ac32** [comment]
I managed 

> Hi @t2ac32. Have you fully removed the black regions around your ultrasound image? If these black pixels are not cropped out, then the response curve calculations will be completely wrong.
> 
> Another problem could be a mismatch in bit-precision. You said you are using 32bit images? The pipeline expects `uint8`.
> 
> Finally, how are you naming the image files? Check to make sure that the file order from ReadLDRStack matches the exposure order. For example `*_1,jpg, *_2.jpg, ... *_11.jpg` will be imported out of order [1, 11, 2]. This can be fixed by renaming the files to `*_01.jpg, *_02.jpg, ... *_11.jpg`

I follow all this recommendations and eventually solved my problems and understanding of the LDR-HDR Converstion.

All my process and technic was publish at **2019 IEEE Symposium (IUS) Ultrasonics**:
[Deep-Learning High-Dynamic-Range Ultrasound](https://ieeexplore.ieee.org/document/8925685/)
